services:

  jenkins:
    image: bitnami/jenkins:2.479.3
    container_name: my_jenkins
    ports:
      - "8081:8080"     # Порт для внешних подключений
      - "50000:50000"   # Внутренний порт для Docker
    environment:
      JENKINS_USERNAME: admin
      JENKINS_PASSWORD: jenkinsAdmin
    volumes:
      - jenkins_data:/bitnami/jenkins
    restart: unless-stopped

  mongodb:
    image: bitnami/mongodb:8.0.4
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: shop_mongo_db
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongo
      MONGODB_ROOT_PASSWORD: mongo

  postgres:
    image: bitnami/postgresql:16.5.0
    container_name: postgres_db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: shop_postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  jenkins_data: